### ISSUE TITLE
FaceShaper cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by xcyhf** [fssorc/ComfyUI_FaceShaper#23]
![未标题-1](https://github.com/user-attachments/assets/8ba128f4-b967-46c9-ae8a-23cc1070e699)

FaceShaper
cannot unpack non-iterable NoneType object
# ComfyUI Error Report
## Error Details
- **Node Type:** FaceShaper
- **Exception Type:** TypeError
- **Exception Message:** cannot unpack non-iterable NoneType object
## Stack Trace
```
  File "D:\comfyui_SD3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\comfyui_SD3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\comfyui_SD3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\comfyui_SD3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 381, in run
    img1,img2 = analysis_models.interpolate(image1,image2,landmarkType,AlignType,True)

  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 130, in interpolate
    landmarks1,leftEye1,rightEye1,mouth1 = self.get_all_landmarks(image1)

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** D:\comfyui_SD3\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 23769529696
  - **Torch VRAM Total:** 268435456
  - **Torch VRAM Free:** 27671904

## Logs
```
2024-11-22 18:34:09,436 - root - INFO - Total VRAM 24564 MB, total RAM 32581 MB
2024-11-22 18:34:09,437 - root - INFO - pytorch version: 2.1.1+cu118
2024-11-22 18:34:09,560 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-22 18:34:09,560 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-22 18:34:09,560 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-22 18:34:10,078 - root - INFO - Using xformers cross attention
2024-11-22 18:34:10,521 - root - INFO - [Prompt Server] web root: D:\comfyui_SD3\web
2024-11-22 18:34:11,506 - root - WARNING - Traceback (most recent call last):
  File "D:\comfyui_SD3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-Anyline\__init__.py", line 1, in <module>
    from .anyline import AnyLine
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-Anyline\anyline.py", line 9, in <module>
    from custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux.teed import TEDDetector
ModuleNotFoundError: No module named 'custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux'

2024-11-22 18:34:11,506 - root - WARNING - Cannot import D:\comfyui_SD3\custom_nodes\ComfyUI-Anyline module for custom nodes: No module named 'custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux'
2024-11-22 18:34:12,800 - numexpr.utils - INFO - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-11-22 18:34:12,800 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-11-22 18:34:13,051 - root - WARNING - Traceback (most recent call last):
  File "D:\comfyui_SD3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui_SD3\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

2024-11-22 18:34:13,051 - root - WARNING - Cannot import D:\comfyui_SD3\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\comfyui_SD3\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
2024-11-22 18:34:13,955 - root - INFO - Total VRAM 24564 MB, total RAM 32581 MB
2024-11-22 18:34:13,955 - root - INFO - pytorch version: 2.1.1+cu118
2024-11-22 18:34:13,955 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-22 18:34:13,956 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-22 18:34:13,956 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-22 18:34:17,682 - root - WARNING - Traceback (most recent call last):
  File "D:\comfyui_SD3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui_SD3\\custom_nodes\\DZ-FaceDetailer\\__init__.py'

2024-11-22 18:34:17,682 - root - WARNING - Cannot import D:\comfyui_SD3\custom_nodes\DZ-FaceDetailer module for custom nodes: [Errno 2] No such file or directory: 'D:\\comfyui_SD3\\custom_nodes\\DZ-FaceDetailer\\__init__.py'
2024-11-22 18:34:21,500 - root - INFO - 
Import times for custom nodes:
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Photopea
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\websocket_image_save.py
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\sdxl_prompt_styler
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\cg-use-everywhere
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\cg-image-picker
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-WD14-Tagger
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\Comfyui_CXH_joy_caption
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\masquerade-nodes-comfyui
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_InstantID
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Image-Saver
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui-inpaint-nodes
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-TiledDiffusion
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\comfyui_SD3\custom_nodes\ComfyUI-CLIPSeg
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\comfyui_SD3\custom_nodes\DZ-FaceDetailer
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Prompt-Preview
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_FizzNodes
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfy-image-saver
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_essentials
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Florence2
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyMath
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui-various
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\OneButtonPrompt
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Custom-Scripts
2024-11-22 18:34:21,500 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-utils-nodes
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\rgthree-comfy
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\x-flux-comfyui
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\efficiency-nodes-comfyui
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Kolors-MZ
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui_controlnet_aux
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui-tensorops
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_tinyterraNodes
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\facerestore_cf
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-KJNodes
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui_bmab
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Inspire-Pack
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\CharacterFaceSwap
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\comfyui-reactor-node
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Crystools
2024-11-22 18:34:21,501 - root - INFO -    0.0 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_LayerStyle
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\PuLID_ComfyUI
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Easy-Use
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-UltraPixel
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Manager
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-22 18:34:21,501 - root - INFO -    0.1 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-PuLID-Flux
2024-11-22 18:34:21,501 - root - INFO -    0.2 seconds: D:\comfyui_SD3\custom_nodes\comfyui_facetools
2024-11-22 18:34:21,501 - root - INFO -    0.2 seconds: D:\comfyui_SD3\custom_nodes\clipseg.py
2024-11-22 18:34:21,501 - root - INFO -    0.2 seconds (IMPORT FAILED): D:\comfyui_SD3\custom_nodes\ComfyUI-Anyline
2024-11-22 18:34:21,501 - root - INFO -    0.3 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Impact-Pack
2024-11-22 18:34:21,501 - root - INFO -    0.4 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-SUPIR
2024-11-22 18:34:21,501 - root - INFO -    0.5 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-11-22 18:34:21,501 - root - INFO -    1.5 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI-BrushNet
2024-11-22 18:34:21,501 - root - INFO -    2.4 seconds: D:\comfyui_SD3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-22 18:34:21,501 - root - INFO -    3.7 seconds: D:\comfyui_SD3\custom_nodes\was-node-suite-comfyui
2024-11-22 18:34:21,501 - root - INFO - 
2024-11-22 18:34:21,512 - root - INFO - Starting server

2024-11-22 18:34:21,512 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-22 18:34:24,124 - openai._base_client - INFO - Retrying request to /models in 0.973896 seconds
2024-11-22 18:34:25,146 - openai._base_client - INFO - Retrying request to /models in 1.734029 seconds
2024-11-22 18:34:26,923 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'RandomNSP _O' node.
2024-11-22 18:34:26,924 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1448, in connect
    super().connect()
  File "D:\comfyui_SD3\python\lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
  File "D:\comfyui_SD3\python\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\comfyui_SD3\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\comfyui_SD3\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\comfyui_SD3\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1100, in INPUT_TYPES
    "terminology": (s.laodCategories(),),
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1090, in laodCategories
    nspterminology = laodNSP()
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1070, in laodNSP
    response = urlopen(
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

2024-11-22 18:34:26,931 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'ConcatRandomNSP_O' node.
2024-11-22 18:34:26,931 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\comfyui_SD3\python\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\comfyui_SD3\python\lib\http\client.py", line 1448, in connect
    super().connect()
  File "D:\comfyui_SD3\python\lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
  File "D:\comfyui_SD3\python\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\comfyui_SD3\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\comfyui_SD3\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\comfyui_SD3\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1132, in INPUT_TYPES
    "terminology": (s.laodCategories(),),
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1121, in laodCategories
    nspterminology = laodNSP()
  File "D:\comfyui_SD3\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\QualityOfLifeSuit_Omar92.py", line 1070, in laodNSP
    response = urlopen(
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\comfyui_SD3\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

2024-11-22 18:34:45,588 - root - INFO - got prompt
2024-11-22 18:34:47,978 - root - ERROR - !!! Exception during processing !!! cannot unpack non-iterable NoneType object
2024-11-22 18:34:47,979 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui_SD3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui_SD3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 381, in run
    img1,img2 = analysis_models.interpolate(image1,image2,landmarkType,AlignType,True)
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 130, in interpolate
    landmarks1,leftEye1,rightEye1,mouth1 = self.get_all_landmarks(image1)
TypeError: cannot unpack non-iterable NoneType object

2024-11-22 18:34:47,980 - root - INFO - Prompt executed in 2.17 seconds
2024-11-22 18:35:16,423 - root - INFO - got prompt
2024-11-22 18:35:16,797 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui_SD3\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui_SD3\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-22 18:35:16,830 - root - ERROR - !!! Exception during processing !!! cannot unpack non-iterable NoneType object
2024-11-22 18:35:16,830 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui_SD3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui_SD3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 381, in run
    img1,img2 = analysis_models.interpolate(image1,image2,landmarkType,AlignType,True)
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 130, in interpolate
    landmarks1,leftEye1,rightEye1,mouth1 = self.get_all_landmarks(image1)
TypeError: cannot unpack non-iterable NoneType object

2024-11-22 18:35:16,831 - root - INFO - Prompt executed in 0.18 seconds
2024-11-22 18:37:58,671 - root - INFO - got prompt
2024-11-22 18:37:59,078 - root - ERROR - !!! Exception during processing !!! cannot unpack non-iterable NoneType object
2024-11-22 18:37:59,079 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui_SD3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfyui_SD3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui_SD3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 381, in run
    img1,img2 = analysis_models.interpolate(image1,image2,landmarkType,AlignType,True)
  File "D:\comfyui_SD3\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 130, in interpolate
    landmarks1,leftEye1,rightEye1,mouth1 = self.get_all_landmarks(image1)
TypeError: cannot unpack non-iterable NoneType object

2024-11-22 18:37:59,079 - root - INFO - Prompt executed in 0.18 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by wstcwszzx** [comment]
same error

**Comment by Positliver** [comment]
same error

**Comment by githust66** [comment]
same error

**Comment by virushe** [comment]
I debugged this part of the code and found that the error was that one of the images passed in did not recognize the face, causing the code to directly return a None value. This None value cannot be unpacked and assigned to the four parameters. You can try to change a few pictures. Some seemingly obvious faces may not be recognized because the face accounts for too large a proportion of the entire image. Try to choose some half-body pictures that are of moderate size and not prone to errors. The error of not being able to recognize this is caused by the face recognition algorithm, which is provided by dlib, so the easiest solution is to change the picture.
