### ISSUE TITLE
NameError: name 'dlib' is not defined. Did you mean: 'DLib'?

### ISSUE THREAD

**Issue by zoranZheng** [fssorc/ComfyUI_FaceShaper#24]
!!! Exception during processing !!! name 'dlib' is not defined
Traceback (most recent call last):
  File "G:\comfyui_001\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\comfyui_001\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\comfyui_001\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\comfyui_001\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\comfyui_001\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 275, in load_models
    out = DLib(DetectType)
          ^^^^^^^^^^^^^^^^
  File "G:\comfyui_001\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 44, in __init__
    self.face_detector = dlib.get_frontal_face_detector()
                         ^^^^
_**NameError: name 'dlib' is not defined. Did you mean: 'DLib'?**_

大佬，显示代码有误是什么情况？请指点一二。

**Comment by zoranZheng** [comment]
不好意思没仔细阅读，已经找到如何解决了

**Comment by mindels0** [comment]
> 不好意思没仔细阅读，已经找到如何解决了

Can you help me with that ?
