### ISSUE TITLE
NameError: name 'dlib' is not defined

### ISSUE THREAD

**Issue by ameen-roayan** [fssorc/ComfyUI_FaceShaper#6]
ompt executed in 0.05 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! name 'dlib' is not defined
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 252, in load_models
    out = DLib(DetectType)
          ^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 22, in __init__
    self.face_detector = dlib.get_frontal_face_detector()
                         ^^^^
NameError: name 'dlib' is not defined

Prompt executed in 0.05 seconds

i get this despite having Dlib installed already

**Comment by xox1234reddit** [comment]
Same issue, or similar -- 

Error occurred when executing FaceShaperModels:

name 'dlib' is not defined

File "C:\Users\USER\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 252, in load_models
out = DLib(DetectType)
^^^^^^^^^^^^^^^^
File "C:\Users\USER\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceShaper\__init__.py", line 22, in __init__
self.face_detector = dlib.get_frontal_face_detector()
^^^^

**Comment by fssorc** [comment]
try V2 please, dlib is nightmare
